---
- name: '{{ ansible_name_module }} | Install required pip library'
  pip:
    name: openshift
    state: present

- name: '{{ ansible_name_module }} | Ensure Proper Python dependency is installed for Openshift'
  python_requirements_facts:
    dependencies:
      - openshift
      - requests

- name: '{{ ansible_name_module }} | shell | Discover oc install directory '
  shell: which oc
  register: oc_location

- name: '{{ ansible_name_module }} | set_fact | Set openshift_cli  '
  set_fact:
    openshift_cli: "{{ oc_location.stdout }}"
  when:
    - not openshift_cli is defined or openshift_cli == ""
    - oc_location is defined
    - oc_location.stdout is defined and not oc_location.stdout == ""

- name: '{{ ansible_name_module }} | Authenticate with the API'
  command: >
    {{ openshift_cli }} login \
      -u {{ ocp_cluster_admin_user }} \
      -p {{ ocp_cluster_admin_password }} \
      --insecure-skip-tls-verify=true {{ ocp_cluster_console_url }}:{{ ocp_cluster_console_port }}
  register: login_out

- name: '{{ ansible_name_module }} | Find operator manifests'
  import_tasks: fetch-operator-catalogs-and-icsp-files.yml 

- name: '{{ ansible_name_module }} | command | deploy ICSP files'
  command: >
    {{ openshift_cli }} apply -f {{ item }} 
  loop: "{{ icsp_file_paths }}"
  when:
    - icsp_file_paths is defined
    - icsp_file_paths | length > 0
  register: op_icsp_applied

- name: '{{ ansible_name_module }} | command | deploy ICSP files'
  command: >
    {{ openshift_cli }} apply -f {{ item }} 
  loop: "{{ catsrcs_file_paths }}"
  when:
    - catsrcs_file_paths is defined
    - catsrcs_file_paths | length > 0
  register: op_catsrcs_applied

